# Generated by Django 3.1.2 on 2020-10-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', upload_to='empimages'),
        ),
    ]
