# Generated by Django 3.1.2 on 2020-10-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20201025_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobileno',
        ),
    ]
