-- Code autogenerated by crc code generator 
-- https://github.com/veeYceeY/codegen-rtl.git



entity crc32 is 
	port(
		i_data : std_logic_vector(31 downto 0);
		i_crc : std_logic_vector(31 downto 0);
		o_crc  : std_logic_vector(31 downto 0)
	);
end entity;

architecture behavioral of crc32 is
	signal d: std_logic_vector(31 downto 0);
	signal c: std_logic_vector(31 downto 0);
begin

  d<= i_data;
  o_crc<= c;
  c(31)=d(31)+i_crc(31)+d(30)+i_crc(30)+d(29)+i_crc(29)+d(28)+i_crc(28)+d(27)+i_crc(27)+d(25)+i_crc(25)+d(24)+i_crc(24)+d(23)+i_crc(23)+d(15)+i_crc(15)+d(11)+i_crc(11)+d(9)+i_crc(9)+d(8)+i_crc(8)+d(5)+i_crc(5)+;
  c(30)=d(30)+i_crc(30)+d(29)+i_crc(29)+d(28)+i_crc(28)+d(27)+i_crc(27)+d(26)+i_crc(26)+d(24)+i_crc(24)+d(23)+i_crc(23)+d(22)+i_crc(22)+d(14)+i_crc(14)+d(10)+i_crc(10)+d(8)+i_crc(8)+d(7)+i_crc(7)+d(4)+i_crc(4)+;
  c(29)=d(31)+i_crc(31)+d(29)+i_crc(29)+d(28)+i_crc(28)+d(27)+i_crc(27)+d(26)+i_crc(26)+d(25)+i_crc(25)+d(23)+i_crc(23)+d(22)+i_crc(22)+d(21)+i_crc(21)+d(13)+i_crc(13)+d(9)+i_crc(9)+d(7)+i_crc(7)+d(6)+i_crc(6)+d(3)+i_crc(3)+;
  c(28)=d(30)+i_crc(30)+d(28)+i_crc(28)+d(27)+i_crc(27)+d(26)+i_crc(26)+d(25)+i_crc(25)+d(24)+i_crc(24)+d(22)+i_crc(22)+d(21)+i_crc(21)+d(20)+i_crc(20)+d(12)+i_crc(12)+d(8)+i_crc(8)+d(6)+i_crc(6)+d(5)+i_crc(5)+d(2)+i_crc(2)+;
  c(27)=d(29)+i_crc(29)+d(27)+i_crc(27)+d(26)+i_crc(26)+d(25)+i_crc(25)+d(24)+i_crc(24)+d(23)+i_crc(23)+d(21)+i_crc(21)+d(20)+i_crc(20)+d(19)+i_crc(19)+d(11)+i_crc(11)+d(7)+i_crc(7)+d(5)+i_crc(5)+d(4)+i_crc(4)+d(1)+i_crc(1)+;
  c(26)=d(31)+i_crc(31)+d(28)+i_crc(28)+d(26)+i_crc(26)+d(25)+i_crc(25)+d(24)+i_crc(24)+d(23)+i_crc(23)+d(22)+i_crc(22)+d(20)+i_crc(20)+d(19)+i_crc(19)+d(18)+i_crc(18)+d(10)+i_crc(10)+d(6)+i_crc(6)+d(4)+i_crc(4)+d(3)+i_crc(3)+d(0)+i_crc(0);
  c(25)=d(31)+i_crc(31)+d(29)+i_crc(29)+d(28)+i_crc(28)+d(22)+i_crc(22)+d(21)+i_crc(21)+d(19)+i_crc(19)+d(18)+i_crc(18)+d(17)+i_crc(17)+d(15)+i_crc(15)+d(11)+i_crc(11)+d(8)+i_crc(8)+d(3)+i_crc(3)+d(2)+i_crc(2)+;
  c(24)=d(30)+i_crc(30)+d(28)+i_crc(28)+d(27)+i_crc(27)+d(21)+i_crc(21)+d(20)+i_crc(20)+d(18)+i_crc(18)+d(17)+i_crc(17)+d(16)+i_crc(16)+d(14)+i_crc(14)+d(10)+i_crc(10)+d(7)+i_crc(7)+d(2)+i_crc(2)+d(1)+i_crc(1)+;
  c(23)=d(31)+i_crc(31)+d(29)+i_crc(29)+d(27)+i_crc(27)+d(26)+i_crc(26)+d(20)+i_crc(20)+d(19)+i_crc(19)+d(17)+i_crc(17)+d(16)+i_crc(16)+d(15)+i_crc(15)+d(13)+i_crc(13)+d(9)+i_crc(9)+d(6)+i_crc(6)+d(1)+i_crc(1)+d(0)+i_crc(0);
  c(22)=d(31)+i_crc(31)+d(29)+i_crc(29)+d(27)+i_crc(27)+d(26)+i_crc(26)+d(24)+i_crc(24)+d(23)+i_crc(23)+d(19)+i_crc(19)+d(18)+i_crc(18)+d(16)+i_crc(16)+d(14)+i_crc(14)+d(12)+i_crc(12)+d(11)+i_crc(11)+d(9)+i_crc(9)+d(0)+i_crc(0);
  c(21)=d(31)+i_crc(31)+d(29)+i_crc(29)+d(27)+i_crc(27)+d(26)+i_crc(26)+d(24)+i_crc(24)+d(22)+i_crc(22)+d(18)+i_crc(18)+d(17)+i_crc(17)+d(13)+i_crc(13)+d(10)+i_crc(10)+d(9)+i_crc(9)+d(5)+i_crc(5)+;
  c(20)=d(30)+i_crc(30)+d(28)+i_crc(28)+d(26)+i_crc(26)+d(25)+i_crc(25)+d(23)+i_crc(23)+d(21)+i_crc(21)+d(17)+i_crc(17)+d(16)+i_crc(16)+d(12)+i_crc(12)+d(9)+i_crc(9)+d(8)+i_crc(8)+d(4)+i_crc(4)+;
  c(19)=d(29)+i_crc(29)+d(27)+i_crc(27)+d(25)+i_crc(25)+d(24)+i_crc(24)+d(22)+i_crc(22)+d(20)+i_crc(20)+d(16)+i_crc(16)+d(15)+i_crc(15)+d(11)+i_crc(11)+d(8)+i_crc(8)+d(7)+i_crc(7)+d(3)+i_crc(3)+;
  c(18)=d(31)+i_crc(31)+d(28)+i_crc(28)+d(26)+i_crc(26)+d(24)+i_crc(24)+d(23)+i_crc(23)+d(21)+i_crc(21)+d(19)+i_crc(19)+d(15)+i_crc(15)+d(14)+i_crc(14)+d(10)+i_crc(10)+d(7)+i_crc(7)+d(6)+i_crc(6)+d(2)+i_crc(2)+;
  c(17)=d(31)+i_crc(31)+d(30)+i_crc(30)+d(27)+i_crc(27)+d(25)+i_crc(25)+d(23)+i_crc(23)+d(22)+i_crc(22)+d(20)+i_crc(20)+d(18)+i_crc(18)+d(14)+i_crc(14)+d(13)+i_crc(13)+d(9)+i_crc(9)+d(6)+i_crc(6)+d(5)+i_crc(5)+d(1)+i_crc(1)+;
  c(16)=d(30)+i_crc(30)+d(29)+i_crc(29)+d(26)+i_crc(26)+d(24)+i_crc(24)+d(22)+i_crc(22)+d(21)+i_crc(21)+d(19)+i_crc(19)+d(17)+i_crc(17)+d(13)+i_crc(13)+d(12)+i_crc(12)+d(8)+i_crc(8)+d(5)+i_crc(5)+d(4)+i_crc(4)+d(0)+i_crc(0);
  c(15)=d(30)+i_crc(30)+d(27)+i_crc(27)+d(24)+i_crc(24)+d(21)+i_crc(21)+d(20)+i_crc(20)+d(18)+i_crc(18)+d(16)+i_crc(16)+d(15)+i_crc(15)+d(12)+i_crc(12)+d(9)+i_crc(9)+d(8)+i_crc(8)+d(7)+i_crc(7)+d(5)+i_crc(5)+d(4)+i_crc(4)+d(3)+i_crc(3)+;
  c(14)=d(29)+i_crc(29)+d(26)+i_crc(26)+d(23)+i_crc(23)+d(20)+i_crc(20)+d(19)+i_crc(19)+d(17)+i_crc(17)+d(15)+i_crc(15)+d(14)+i_crc(14)+d(11)+i_crc(11)+d(8)+i_crc(8)+d(7)+i_crc(7)+d(6)+i_crc(6)+d(4)+i_crc(4)+d(3)+i_crc(3)+d(2)+i_crc(2)+;
  c(13)=d(31)+i_crc(31)+d(28)+i_crc(28)+d(25)+i_crc(25)+d(22)+i_crc(22)+d(19)+i_crc(19)+d(18)+i_crc(18)+d(16)+i_crc(16)+d(14)+i_crc(14)+d(13)+i_crc(13)+d(10)+i_crc(10)+d(7)+i_crc(7)+d(6)+i_crc(6)+d(5)+i_crc(5)+d(3)+i_crc(3)+d(2)+i_crc(2)+d(1)+i_crc(1)+;
  c(12)=d(31)+i_crc(31)+d(30)+i_crc(30)+d(27)+i_crc(27)+d(24)+i_crc(24)+d(21)+i_crc(21)+d(18)+i_crc(18)+d(17)+i_crc(17)+d(15)+i_crc(15)+d(13)+i_crc(13)+d(12)+i_crc(12)+d(9)+i_crc(9)+d(6)+i_crc(6)+d(5)+i_crc(5)+d(4)+i_crc(4)+d(2)+i_crc(2)+d(1)+i_crc(1)+d(0)+i_crc(0);
  c(11)=d(31)+i_crc(31)+d(28)+i_crc(28)+d(27)+i_crc(27)+d(26)+i_crc(26)+d(25)+i_crc(25)+d(24)+i_crc(24)+d(20)+i_crc(20)+d(17)+i_crc(17)+d(16)+i_crc(16)+d(15)+i_crc(15)+d(14)+i_crc(14)+d(12)+i_crc(12)+d(9)+i_crc(9)+d(4)+i_crc(4)+d(3)+i_crc(3)+d(1)+i_crc(1)+d(0)+i_crc(0);
  c(10)=d(31)+i_crc(31)+d(29)+i_crc(29)+d(28)+i_crc(28)+d(26)+i_crc(26)+d(19)+i_crc(19)+d(16)+i_crc(16)+d(14)+i_crc(14)+d(13)+i_crc(13)+d(9)+i_crc(9)+d(5)+i_crc(5)+d(3)+i_crc(3)+d(2)+i_crc(2)+d(0)+i_crc(0);
  c(9)=d(29)+i_crc(29)+d(24)+i_crc(24)+d(23)+i_crc(23)+d(18)+i_crc(18)+d(13)+i_crc(13)+d(12)+i_crc(12)+d(11)+i_crc(11)+d(9)+i_crc(9)+d(5)+i_crc(5)+d(4)+i_crc(4)+d(2)+i_crc(2)+d(1)+i_crc(1)+;
  c(8)=d(31)+i_crc(31)+d(28)+i_crc(28)+d(23)+i_crc(23)+d(22)+i_crc(22)+d(17)+i_crc(17)+d(12)+i_crc(12)+d(11)+i_crc(11)+d(10)+i_crc(10)+d(8)+i_crc(8)+d(4)+i_crc(4)+d(3)+i_crc(3)+d(1)+i_crc(1)+d(0)+i_crc(0);
  c(7)=d(29)+i_crc(29)+d(28)+i_crc(28)+d(25)+i_crc(25)+d(24)+i_crc(24)+d(23)+i_crc(23)+d(22)+i_crc(22)+d(21)+i_crc(21)+d(16)+i_crc(16)+d(15)+i_crc(15)+d(10)+i_crc(10)+d(8)+i_crc(8)+d(7)+i_crc(7)+d(5)+i_crc(5)+d(3)+i_crc(3)+d(2)+i_crc(2)+d(0)+i_crc(0);
  c(6)=d(30)+i_crc(30)+d(29)+i_crc(29)+d(25)+i_crc(25)+d(22)+i_crc(22)+d(21)+i_crc(21)+d(20)+i_crc(20)+d(14)+i_crc(14)+d(11)+i_crc(11)+d(8)+i_crc(8)+d(7)+i_crc(7)+d(6)+i_crc(6)+d(5)+i_crc(5)+d(4)+i_crc(4)+d(2)+i_crc(2)+d(1)+i_crc(1)+;
  c(5)=d(29)+i_crc(29)+d(28)+i_crc(28)+d(24)+i_crc(24)+d(21)+i_crc(21)+d(20)+i_crc(20)+d(19)+i_crc(19)+d(13)+i_crc(13)+d(10)+i_crc(10)+d(7)+i_crc(7)+d(6)+i_crc(6)+d(5)+i_crc(5)+d(4)+i_crc(4)+d(3)+i_crc(3)+d(1)+i_crc(1)+d(0)+i_crc(0);
  c(4)=d(31)+i_crc(31)+d(30)+i_crc(30)+d(29)+i_crc(29)+d(25)+i_crc(25)+d(24)+i_crc(24)+d(20)+i_crc(20)+d(19)+i_crc(19)+d(18)+i_crc(18)+d(15)+i_crc(15)+d(12)+i_crc(12)+d(11)+i_crc(11)+d(8)+i_crc(8)+d(6)+i_crc(6)+d(4)+i_crc(4)+d(3)+i_crc(3)+d(2)+i_crc(2)+d(0)+i_crc(0);
  c(3)=d(31)+i_crc(31)+d(27)+i_crc(27)+d(25)+i_crc(25)+d(19)+i_crc(19)+d(18)+i_crc(18)+d(17)+i_crc(17)+d(15)+i_crc(15)+d(14)+i_crc(14)+d(10)+i_crc(10)+d(9)+i_crc(9)+d(8)+i_crc(8)+d(7)+i_crc(7)+d(3)+i_crc(3)+d(2)+i_crc(2)+d(1)+i_crc(1)+;
  c(2)=d(31)+i_crc(31)+d(30)+i_crc(30)+d(26)+i_crc(26)+d(24)+i_crc(24)+d(18)+i_crc(18)+d(17)+i_crc(17)+d(16)+i_crc(16)+d(14)+i_crc(14)+d(13)+i_crc(13)+d(9)+i_crc(9)+d(8)+i_crc(8)+d(7)+i_crc(7)+d(6)+i_crc(6)+d(2)+i_crc(2)+d(1)+i_crc(1)+d(0)+i_crc(0);
  c(1)=d(28)+i_crc(28)+d(27)+i_crc(27)+d(24)+i_crc(24)+d(17)+i_crc(17)+d(16)+i_crc(16)+d(13)+i_crc(13)+d(12)+i_crc(12)+d(11)+i_crc(11)+d(9)+i_crc(9)+d(7)+i_crc(7)+d(6)+i_crc(6)+d(1)+i_crc(1)+d(0)+i_crc(0);
  c(0)=d(31)+i_crc(31)+d(30)+i_crc(30)+d(29)+i_crc(29)+d(28)+i_crc(28)+d(26)+i_crc(26)+d(25)+i_crc(25)+d(24)+i_crc(24)+d(16)+i_crc(16)+d(12)+i_crc(12)+d(10)+i_crc(10)+d(9)+i_crc(9)+d(6)+i_crc(6)+d(0)+i_crc(0);


end architecture ;