# Generated by Django 3.1.2 on 2020-10-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numconversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converted',
            name='audio',
            field=models.FileField(upload_to=None),
        ),
    ]
