# Generated by Django 3.1.2 on 2020-10-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numconversion', '0002_auto_20201027_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='converted',
        ),
    ]
